### ISSUE TITLE
Does ngraph optimize InceptionV3 topology?

### ISSUE THREAD

**Issue by felipheggaliza** [NervanaSystems/ngraph-tf#202]
Does ngraph optimize InceptionV3 topology?
What are the topologies which we can expect a performance improvement when using nGraph?

**Comment by sharathns93** [comment]
Hi,
Thanks for trying out ngraph-tf. InceptionV3 is optimized on nGraph. Currently most of the image recognition models are optimized through nGraph and we should expect to see performance improvements when run with NCHW data format. Optimizations for object detection and language translation topologies are being worked on.
