### ISSUE TITLE
Illegal instruction (core dumped) when trying to run ngraph-bridge

### ISSUE THREAD

**Issue by vandersonmr** [NervanaSystems/ngraph-tf#356]
Hi everyone,

I'm trying to run a simple TF CNN-mnist example with ngraph but I receive the following error when tf.train is called: Illegal instruction (core dumped).
When I run the code without importing ngraph_bridge it works perfectly. 

How could I debug it and get more information about what is happening? Does anyone have clue about what could it be? 

Thank you.

**Comment by mingshan-wang** [comment]
Hi @vandersonmr, could you please provide more system information? 

OS Platform and Distribution: 
How did you build ngraph_bridge: 
Python version: 
GCC/Compiler version (gcc --version):

Thank you!

**Comment by avijit-nervana** [comment]
Since we didn't get any response, assuming that this was resolved. Please report back if there is still an issue.
